name: genshin_chat
description: "纯本地原神角色聊天 Android 应用。"
publish_to: 'none'
version: 1.9.1+19

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data/characters.json
